import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def generate_m3_summary():
    print("Loading simulation metrics...")
    
    try:
        # Load the newly generated data
        df = pd.read_csv("simulation_metrics.csv")
    except FileNotFoundError:
        print("Error: simulation_metrics.csv not found. Please run main.py first.")
        return

    # Group by run_id and calculate key metrics
    summary = df.groupby('run_id').agg(
        Total_Planes_Processed=('aircraft', 'count'),
        Avg_Wait_Time_mins=('wait_time', 'mean'),
        Avg_Weather_Delay_mins=('weather_delay_mins', 'mean'),
        Avg_Turnaround_Time_mins=('total_turnaround_time', 'mean'),
        Max_Wait_Time_mins=('wait_time', 'max')
    ).round(2)

    # Add descriptive scenario names to match the 10 variations
    scenario_names = [
        "1. Run 1", 
        "2. Run 2", 
        "3. Run 3", 
        "4. Run 4", 
        "5. Run 5", 
        "6. Run 6", 
        "7. Run 7", 
        "8. Run 8", 
        "9. Run 9", 
        "10. Run 10"
    ]
    
    # Insert the scenario names as the first column
    summary.insert(0, 'Scenario_Description', scenario_names)

    # Print the table in Markdown format
    print("\n" + "="*60)
    print("MILESTONE 3: RUN SUMMARY TABLE")
    print("="*60 + "\n")
    print(summary.to_markdown(index=False))
    print("\n" + "="*60)

    def generate_trend_chart():
        # Load the data generated by main.py
        try:
            df = pd.read_csv("simulation_metrics.csv")
        except FileNotFoundError:
            print("Error: 'simulation_metrics.csv' not found. Please run main.py first.")
            return

    run_col = 'run_id'
    wait_col = 'wait_time' 
    turnaround_col = 'total_turnaround_time'

    # Group the data by Run ID to get the average metrics for each specific scenario
    summary_df = df.groupby(run_col)[[wait_col, turnaround_col]].mean().reset_index()

    # Create the Chart Figure
    plt.figure(figsize=(10, 6))

    # Plot Wait Time (offset slightly to the left)
    plt.bar(summary_df[run_col] - 0.2, summary_df[wait_col], 
            width=0.4, label='Avg Wait Time', color='coral')
    
    # Plot Total Turnaround Time (offset slightly to the right)
    plt.bar(summary_df[run_col] + 0.2, summary_df[turnaround_col], 
            width=0.4, label='Avg Turnaround Time', color='skyblue')

    # 4. Formatting and Labels
    plt.xlabel('Simulation Run ID', fontsize=12, fontweight='bold')
    plt.ylabel('Time (Minutes)', fontsize=12, fontweight='bold')
    plt.title('Average Wait vs. Turnaround Time per Simulation Run', fontsize=14)
    plt.xticks(summary_df[run_col]) # Ensure every run ID is labeled on the X-axis
    plt.legend()

    # 5. Save the image
    plt.tight_layout()
    plt.savefig('run_trends_chart.png', dpi=300)
    
    # Show the plot on screen
    plt.show()

if __name__ == "__main__":
    generate_m3_summary()
    