import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Got rid of generate_m3_summary()

def generate_statistical_summary():
    print("--- M4 Statistical Summary (Wait Times) ---")
    
    # 1. Load the raw data generated by main.py
    try:
        df = pd.read_csv("simulation_metrics.csv")
    except FileNotFoundError:
        print("Error: simulation_metrics.csv not found. Run main.py first.")
        return

    # 2. Group by BOTH run_id and replication_id to get the daily averages
    # We want the average wait time for each individual 8-hour shift first
    daily_averages = df.groupby(['run_id', 'replication_id'])['wait_time'].mean().reset_index()

    # 3. Now group by run_id to calculate the overall stats across the 10 replications
    summary_stats = daily_averages.groupby('run_id')['wait_time'].agg(
        mean_wait='mean',
        std_wait='std',
        min_wait='min',
        max_wait='max',
        n_runs='count'
    ).reset_index()

    # 4. Calculate the 95% Confidence Interval using the M4 Formula
    # CI = mean +/- 1.96 * (std / sqrt(n))
    summary_stats['margin_of_error'] = 1.96 * (summary_stats['std_wait'] / np.sqrt(summary_stats['n_runs']))
    summary_stats['ci_lower'] = summary_stats['mean_wait'] - summary_stats['margin_of_error']
    summary_stats['ci_upper'] = summary_stats['mean_wait'] + summary_stats['margin_of_error']

    # Formatting for clean output
    summary_stats = summary_stats.round(2)
    
    for index, row in summary_stats.iterrows():
        print(f"Run {int(row['run_id'])}:")
        print(f"  Mean Wait: {row['mean_wait']} mins (Std Dev: {row['std_wait']})")
        print(f"  95% CI:    [{row['ci_lower']}, {row['ci_upper']}]")
        print(f"  Range:     {row['min_wait']} to {row['max_wait']} mins\n")

    return summary_stats

if __name__ == "__main__":

    # Generate the stats and Confidence Intervals
    stats = generate_statistical_summary()
